### ISSUE TITLE
Test view by board - Total test suite number is wrong

### ISSUE THREAD

**Issue by loysollivier** [kernelci/kernelci-frontend#26]
As an example: 
https://kernelci.org/test/board/bcm2837-rpi-3-b/
The total test suite count reports 9 test suites available for broonie-regmap but only 1 is visible when selecting this entry in the table:
https://kernelci.org/test/board/bcm2837-rpi-3-b/job/broonie-regmap/

Probably something off with the batch count and the 14 days data filter...

**Comment by gctucker** [comment]
This will go away as part of #43 as we're planning to replace the tests view altogether.
