### ISSUE TITLE
Tests-suite view: wrong links in the page header

### ISSUE THREAD

**Issue by ndechesne** [kernelci/kernelci-frontend#29]
In the view "test details for test suite" the page header includes links to tests for the same board, lab, tree, but they link to unexisting page. 

e.g. 

https://kernelci.org/test/suite/5b10d2da59b51471be79a888/

which has link to 
* https://kernelci.org/test/all/lab/lab-bjorn/
* https://kernelci.org/test/apq8096-db820c/
* https://kernelci.org/test/all/job/mainline/

All lead to this message: 
"This is not the web page you are looking for. 
You can go about your businness. 
Move along… Move along…"

**Comment by gctucker** [comment]
It seems that this may just go away as part of porting the AGL version of their test view as per #43.

**Comment by gctucker** [comment]
This is not applicable any more with the new set of views on https://staging.kernelci.org (to be rolled out soon on https://kernelci.org).
