### ISSUE TITLE
SoC RSS feed does not have "git describe" value

### ISSUE THREAD

**Issue by MiloCasagrande** [kernelci/kernelci-frontend#3]
The RSS feed for a SoC (like [amlogic](https://kernelci.org/soc/amlogic/feed.xml), [davinci](https://kernelci.org/soc/davinci/feed.xml)), does not contain in the title/subject the "git describe" value (aka the "kernel" value).

**Comment by gctucker** [comment]
There doesn't appear to be any demand for RSS feeds any more, so closing this issue.
