### ISSUE TITLE
Per-job date or data range 

### ISSUE THREAD

**Issue by mattface** [kernelci/kernelci-frontend#30]
Moved from Linaros JIRA:

As per Kevin's request, we need a way to whitelist some of the trees/jobs in order to show more data.

This is due to the fact that trees like stable and LSK do not have the same amount of changes as other trees do, and the default 14-days date range might be too small for them.

**Comment by gctucker** [comment]
This seems like something that will go away as part of designing a better dashboard.  I don't think anyone is going to be implementing this feature in the current kernelci-frontend.  Are we OK with closing this issue now?

@khilman @mattface

**Comment by gctucker** [comment]
Closing as this is still not in the planned work, and a new web UI would solve this issue differently.
