### ISSUE TITLE
Add branch selection in compare view

### ISSUE THREAD

**Issue by mattface** [kernelci/kernelci-frontend#32]
Moved from Linaro JIRA:

When doing a comparison, add a Branch field tied to the kernel on in order to select its branch (especially when there are more than one).

**Comment by gctucker** [comment]
@mattface I'm not sure the compare view is being maintained any more, can we just close this issue now?

**Comment by gctucker** [comment]
The "compare" views have been dropped, they were not fully working and not deemed worth the effort.  Time should be spent on a new web UI design altogether, with flexible queries to be able to select and compare data more arbitrarily.
