### ISSUE TITLE
Boot reports don't show compiler used clearly

### ISSUE THREAD

**Issue by broonie** [kernelci/kernelci-frontend#44]
The compiler used for a boot is not shown in the main boot status report for a build (eg, https://kernelci.org/boot/all/job/next/branch/master/kernel/next-20190730/) - it is visible in the per boot pages but nowhere else I can see. This means that any conflicts between compilers are not visible and that it's not obvious why what looks like the same build is showing up multiple times in the same lab when the failure affects multiple compilers.

@mattface

**Comment by gctucker** [comment]
Boot reports aren't sent any more, and the test reports show the compiler names.  Please create a new issue if this there is also something to fix in test reports.
