### ISSUE TITLE
boot view, filter by branch

### ISSUE THREAD

**Issue by khilman** [kernelci/kernelci-frontend#9]
Looking at a boot view of a particular job, e.g:

   https://kernelci.org/boot/all/job/stable/

we used to be able to click on a branch name (e.g. linux-4.10.y) add see a similar view but only with that branch.  That seems to have been lost with the updates?

**Comment by MiloCasagrande** [comment]
Hi Kevin,

are you sure we had one?
We don't have a URL rule to handle that, but we can add new one.

**Comment by khilman** [comment]
We definitely had this feature before.  Thanks for making it work again.
